// src/users-data.ts
export const users = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    role: "admin",
    status: "active",
    createdAt: "2023-01-15T09:30:00Z",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    role: "user",
    status: "active",
    createdAt: "2023-02-20T14:22:00Z",
  },
  {
    id: "3",
    name: "Robert Johnson",
    email: "robert.j@example.com",
    role: "user",
    status: "inactive",
    createdAt: "2023-03-05T11:15:00Z",
  },
  {
    id: "4",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    role: "manager",
    status: "active",
    createdAt: "2023-04-12T16:45:00Z",
  },
  {
    id: "5",
    name: "Michael Wilson",
    email: "m.wilson@example.com",
    role: "user",
    status: "pending",
    createdAt: "2023-05-08T10:20:00Z",
  },
  {
    id: "6",
    name: "Sarah Brown",
    email: "sarah.b@example.com",
    role: "user",
    status: "active",
    createdAt: "2023-06-17T08:55:00Z",
  },
  {
    id: "7",
    name: "David Miller",
    email: "david.m@example.com",
    role: "admin",
    status: "active",
    createdAt: "2023-07-22T13:40:00Z",
  },
  {
    id: "8",
    name: "Lisa Taylor",
    email: "lisa.t@example.com",
    role: "user",
    status: "inactive",
    createdAt: "2023-08-30T15:10:00Z",
  },
  {
    id: "9",
    name: "James Anderson",
    email: "j.anderson@example.com",
    role: "manager",
    status: "active",
    createdAt: "2023-09-14T09:25:00Z",
  },
  {
    id: "10",
    name: "Jennifer Thomas",
    email: "j.thomas@example.com",
    role: "user",
    status: "pending",
    createdAt: "2023-10-05T11:35:00Z",
  },
];